(() => {
'use strict';
const C=MyRateConfig,Calc=MyRateCalculator,S=MyRateStorage,$=id=>document.getElementById(id),clone=S.clone,stamp=()=>new Date().toISOString();
let state=S.load(),items=[],unit='hours',openedFavorite=null,openedProject=null,previousScreen='Current',archiveTab='calculations',selectionMode=false,selected=new Set(),toastTimer,magicTimer,magicHideTimer,introActive=false,introHiddenAt=0;
const wheelValues={},wheelDefs={},bags={};
const activeCalcs=()=>state.calculations.filter(x=>x.status!=='archived'),activeProjects=()=>state.projects.filter(x=>x.status!=='archived'),find=(a,id)=>a.find(x=>x.id===id);
const privacy=()=>/iPhone/i.test(navigator.userAgent)?'Мы никуда не отправляем введённые данные. Всё остаётся на этом iPhone.':'Мы никуда не отправляем введённые данные. Всё остаётся на этом устройстве.';
function save(){if(!S.save(state))toast('Не удалось сохранить данные на устройстве.');}
function copy(key){const a=C.copy[key]||['Готово.'];if(!bags[key]?.length)bags[key]=[...a].sort(()=>Math.random()-.5);return bags[key].pop();}
function toast(text,key){clearTimeout(toastTimer);const message=text||copy(key),duration=Math.min(C.toastMaxMs,Math.max(C.toastMinMs,2600+message.length*48));$('toast').textContent=message;$('toast').classList.remove('hidden');toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),duration);}
function magic(key,fn){clearTimeout(magicTimer);clearTimeout(magicHideTimer);const overlay=$('magicOverlay'),done=()=>{overlay.classList.remove('is-visible');magicHideTimer=setTimeout(()=>{overlay.classList.add('hidden');fn?.()},C.magicFadeMs)};if(!state.settings.magic||matchMedia('(prefers-reduced-motion: reduce)').matches){overlay.classList.add('hidden');overlay.classList.remove('is-visible');fn?.();return}const max=key==='fx'?C.magicFxMaxMs:C.magicMaxMs,duration=Math.round(C.magicMinMs+Math.random()*(max-C.magicMinMs));$('magicText').textContent=state.settings.jokes?copy(key):copy('neutral');overlay.classList.remove('is-visible');overlay.classList.add('hidden');void overlay.offsetWidth;overlay.classList.remove('hidden');requestAnimationFrame(()=>requestAnimationFrame(()=>overlay.classList.add('is-visible')));magicTimer=setTimeout(done,duration);}
function closeHelp(){$('helpPopover').classList.add('hidden')}
function dismissKeyboard(){document.activeElement?.blur?.();document.body.classList.remove('keyboard-open')}
function runIntro(mode='launch'){if(introActive)return;const intro=$('introScreen'),title=$('introTitle'),target=$('mainTitle'),theme=document.querySelector('meta[name="theme-color"]'),isReturn=mode==='return',reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,holdMs=isReturn?C.introReturnHoldMs:C.introHoldMs,brandMs=isReturn?C.introReturnBrandMs:C.introBrandMs,started=performance.now();let leaving=false,exitTimer,brandTimer,finishTimer;introActive=true;intro.className='intro-screen hidden';intro.removeAttribute('style');title.className='intro-title';title.removeAttribute('style');document.documentElement.classList.add('intro-pending');const finish=()=>{clearTimeout(exitTimer);clearTimeout(brandTimer);clearTimeout(finishTimer);intro.removeEventListener('pointerup',skip);document.removeEventListener('keydown',key);document.documentElement.classList.remove('intro-pending');document.body.classList.remove('intro-running','intro-handoff','intro-reduced');theme.content='#f2f0ea';intro.classList.add('hidden');introActive=false},leave=()=>{if(leaving)return;leaving=true;clearTimeout(exitTimer);clearTimeout(brandTimer);intro.classList.add('is-branded');const from=title.getBoundingClientRect(),to=target.getBoundingClientRect(),scale=from.width?to.width/from.width:1;title.style.transition='none';title.style.left=`${from.left}px`;title.style.top=`${from.top}px`;title.style.width=`${from.width}px`;title.classList.add('is-frozen');void title.offsetWidth;title.style.removeProperty('transition');intro.style.setProperty('--intro-x',`${to.left-from.left}px`);intro.style.setProperty('--intro-y',`${to.top-from.top}px`);intro.style.setProperty('--intro-scale',String(scale));document.documentElement.classList.remove('intro-pending');document.body.classList.add('intro-handoff');theme.content='#f2f0ea';void title.offsetWidth;requestAnimationFrame(()=>requestAnimationFrame(()=>intro.classList.add('is-leaving')));finishTimer=setTimeout(finish,reduced?620:C.introExitMs+80)},skip=()=>{if(performance.now()-started>=C.introSkipDelayMs)leave()},key=e=>{if(['Escape','Enter',' '].includes(e.key))skip()};theme.content='#10100f';document.body.classList.add('intro-running');if(reduced){intro.classList.add('is-reduced');document.body.classList.add('intro-reduced')}intro.classList.remove('hidden');requestAnimationFrame(()=>intro.classList.add('is-running'));brandTimer=setTimeout(()=>intro.classList.add('is-branded'),reduced?900:brandMs);exitTimer=setTimeout(leave,reduced?1800:holdMs);intro.addEventListener('pointerup',skip);document.addEventListener('keydown',key)}
function setupIntroLifecycle(){const remember=()=>{introHiddenAt=Date.now()},resume=()=>{if(!introHiddenAt)return;const awayFor=Date.now()-introHiddenAt;introHiddenAt=0;if(awayFor>=C.introReturnAfterMs)runIntro('return')};document.addEventListener('visibilitychange',()=>{if(document.hidden)remember();else resume()});window.addEventListener('pagehide',remember);window.addEventListener('pageshow',event=>{if(event.persisted)resume()})}
function showHelp(btn){const box=$('helpPopover'),text=(C.help[btn.dataset.help]||'').replace('{privacy}',privacy());if(!text||(!box.classList.contains('hidden')&&box.dataset.for===btn.dataset.help)){closeHelp();return}box.textContent=text;box.dataset.for=btn.dataset.help;box.classList.remove('hidden');const r=btn.getBoundingClientRect(),w=Math.min(320,innerWidth-28);box.style.width=w+'px';box.style.left=Math.max(14,Math.min(innerWidth-w-14,r.right-w))+'px';box.style.top=Math.min(innerHeight-box.offsetHeight-14,r.bottom+8)+'px'}
function dialog({title,text='',body=null,actions=[{label:'Понятно',value:true,primary:true}]}){return new Promise(resolve=>{const layer=$('dialogLayer'),buttons=[];$('dialogTitle').textContent=title;$('dialogText').textContent=text;$('dialogBody').replaceChildren();if(body)$('dialogBody').append(body);$('dialogActions').innerHTML='';let closed=false;const close=v=>{if(closed)return;closed=true;dismissKeyboard();layer.classList.add('hidden');resolve(v)},refresh=()=>buttons.forEach(({button,action})=>button.disabled=action.enabled?!action.enabled():false);actions.forEach(a=>{const b=document.createElement('button');b.type='button';b.className=`button ${a.primary?'primary':'secondary'} ${a.danger?'danger':''}`;b.textContent=a.label;b.onclick=()=>{if(a.validate&&!a.validate())return;close(a.value)};buttons.push({button:b,action:a});$('dialogActions').append(b)});if(body)['input','change','click'].forEach(type=>body.addEventListener(type,refresh));refresh();$('dialogClose').onclick=()=>close(null);layer.onclick=e=>{if(e.target===layer)close(null)};layer.classList.remove('hidden')})}
async function confirm(title,text,ok='Подтвердить'){return await dialog({title,text,actions:[{label:'Не надо',value:false},{label:ok,value:true,primary:true}]})===true}
async function ask(title,text,value='',kind='title'){const input=document.createElement('input');input.className='dialog-input';input.maxLength=80;input.value=value;input.placeholder='Название';input.required=true;input.setAttribute('aria-required','true');const project=kind==='project',result=await dialog({title,text,body:input,actions:[{label:'Отмена',value:false},{label:'Сохранить',value:true,primary:true,enabled:()=>Boolean(input.value.trim()),validate:()=>validateFields([{input,label:project?'название плана':'название',emptyKey:project?'requiredProjectTitle':'requiredTitle'}])}]});return result?input.value.trim():null}
function sheet(title,actions){const layer=$('sheetLayer');$('sheetTitle').textContent=title;$('sheetActions').innerHTML='';actions.forEach(a=>{const b=document.createElement('button');b.className=`sheet-action ${a.danger?'danger':''}`;b.type='button';b.textContent=a.label;b.onclick=()=>{layer.classList.add('hidden');a.run?.()};$('sheetActions').append(b)});$('sheetCancel').onclick=()=>layer.classList.add('hidden');layer.onclick=e=>{if(e.target===layer)layer.classList.add('hidden')};layer.classList.remove('hidden')}
function sanitize(input){let v=input.value.replace(/\s/g,'').replace(/[^0-9.,]/g,'').replace(',','.');const i=v.indexOf('.');if(i>=0)v=v.slice(0,i+1)+v.slice(i+1).replace(/\./g,'');input.value=v}
function num(id){return Number($(id).value.replace(',','.'))}
function validNumber(input){const v=Number(input.value.replace(',','.')),min=Number(input.dataset.min),max=Number(input.dataset.max);return Number.isFinite(v)&&v>=min&&v<=max}
function clearFieldError(input){input.classList.remove('field-error');input.removeAttribute('aria-invalid')}
function markFieldError(input){input.classList.remove('field-error');void input.offsetWidth;input.classList.add('field-error');input.setAttribute('aria-invalid','true')}
function validateFields(rules){const errors=[];rules.forEach(rule=>{const empty=!String(rule.input.value??'').trim(),invalid=!empty&&rule.valid&&!rule.valid(rule.input);if(empty||invalid){markFieldError(rule.input);errors.push({...rule,key:empty?rule.emptyKey:rule.invalidKey||rule.emptyKey})}else clearFieldError(rule.input)});if(!errors.length)return true;const first=errors[0];if(errors.length===1)toast(null,first.key);else toast(`${copy('requiredMany')} ${errors.map(x=>x.label).join(', ')}.`);return false}
function profileFormReady(){return[$('income'),$('days'),$('hours')].every(validNumber)}
function itemFormReady(){return Boolean($('itemName').value.trim())&&validNumber($('itemPrice'))&&validNumber($('itemQty'))}
function updateFormButtons(){$('saveProfile').disabled=!profileFormReady();$('addItem').disabled=!itemFormReady()}

function setupWheel(name,map,onChange){wheelValues[name]??=Object.keys(map)[0];wheelDefs[name]={entries:Object.entries(map),onChange,commitTimer:null,committedValue:wheelValues[name]};renderWheel(name);}
function paintWheel(root){const offset=Number(root.dataset.offset||0),active=root.classList.contains('is-active'),options=[...root.querySelectorAll('.wheel-option')],position=option=>(Number(option.dataset.distance)+1)*42+offset,focus=options.reduce((best,option)=>Math.abs(position(option)-42)<Math.abs(position(best)-42)?option:best,options[0]);options.forEach(option=>{const y=position(option),distance=Math.abs(y-42)/42,closeness=Math.max(0,1-Math.min(distance,1)),scale=.92+closeness*(active?.25:.16),selected=option===focus;option.style.transform=`translateY(${y}px) scale(${scale})`;option.style.opacity=String(active?.5+closeness*.5:selected?1:0);option.classList.toggle('is-focus',selected);option.setAttribute('aria-selected',selected?'true':'false')})}
function settleWheel(name){const root=document.querySelector(`[data-wheel="${name}"]`),def=wheelDefs[name];if(!root||!def)return;clearTimeout(def.commitTimer);root.classList.remove('is-active','is-dragging');root.classList.add('is-settling');root.dataset.offset='0';paintWheel(root);def.commitTimer=setTimeout(()=>{root.classList.remove('is-settling');if(def.committedValue!==wheelValues[name]){def.committedValue=wheelValues[name];def.onChange?.(wheelValues[name])}},C.wheelSettleMs)}
function renderWheel(name){const root=document.querySelector(`[data-wheel="${name}"]`),def=wheelDefs[name];if(!root||!def)return;let box=root.querySelector('.wheel-options');if(!box){root.replaceChildren();const center=document.createElement('div');center.className='wheel-center';box=document.createElement('div');box.className='wheel-options';[-2,-1,0,1,2].forEach(d=>{const option=document.createElement('div');option.className='wheel-option';option.dataset.distance=d;option.setAttribute('role','option');box.append(option)});root.append(center,box);root.dataset.offset='0';root.tabIndex=0;root.setAttribute('role','listbox');bindWheelGesture(root,name)}const n=def.entries.length,index=Math.max(0,def.entries.findIndex(x=>x[0]===wheelValues[name]));[...box.children].forEach((option,slot)=>{const d=slot-2,idx=(index+d+n)%n,[value,label]=def.entries[idx];option.dataset.distance=d;option.dataset.value=value;option.textContent=label});paintWheel(root)}
function previewWheel(name,value){wheelValues[name]=value;renderWheel(name)}
function selectWheel(name,value,fire=false){wheelValues[name]=value;wheelDefs[name].committedValue=value;renderWheel(name);if(fire)wheelDefs[name].onChange?.(value)}
function bindWheelGesture(root,name){if(root.dataset.gestureBound)return;root.dataset.gestureBound='1';let holdTimer,startY=0,lastY=0,offset=0,active=false;const shift=direction=>{const a=wheelDefs[name].entries,i=a.findIndex(x=>x[0]===wheelValues[name]),next=(i+direction+a.length)%a.length;root.dataset.offset=String(offset);previewWheel(name,a[next][0])};const activate=()=>{active=true;clearTimeout(wheelDefs[name].commitTimer);root.classList.remove('is-settling');root.classList.add('is-active');try{navigator.vibrate?.(6)}catch{};paintWheel(root)};const finish=()=>{clearTimeout(holdTimer);if(!active)return;active=false;if(offset<=-21){offset+=42;shift(1)}else if(offset>=21){offset-=42;shift(-1)}root.dataset.offset=String(offset);settleWheel(name);offset=0};root.addEventListener('contextmenu',e=>e.preventDefault());root.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;startY=lastY=e.touches[0].clientY;offset=Number(root.dataset.offset||0);active=false;clearTimeout(holdTimer);holdTimer=setTimeout(activate,C.wheelHoldMs)},{passive:true});root.addEventListener('touchmove',e=>{if(e.touches.length!==1)return;const y=e.touches[0].clientY;if(!active){if(Math.abs(y-startY)>8)clearTimeout(holdTimer);return}e.preventDefault();if(!root.classList.contains('is-dragging'))root.classList.add('is-dragging');offset+=y-lastY;lastY=y;while(offset<=-42){offset+=42;shift(1)}while(offset>=42){offset-=42;shift(-1)}root.dataset.offset=String(offset);paintWheel(root)},{passive:false});root.addEventListener('touchend',finish,{passive:true});root.addEventListener('touchcancel',finish,{passive:true});root.addEventListener('wheel',e=>{e.preventDefault();const a=wheelDefs[name].entries,i=a.findIndex(x=>x[0]===wheelValues[name]),next=(i+(e.deltaY>0?1:-1)+a.length)%a.length;previewWheel(name,a[next][0]);settleWheel(name)},{passive:false});root.addEventListener('keydown',e=>{if(!['ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const a=wheelDefs[name].entries,i=a.findIndex(x=>x[0]===wheelValues[name]),next=(i+(e.key==='ArrowDown'?1:-1)+a.length)%a.length;previewWheel(name,a[next][0]);settleWheel(name)})}

function profileFromForm(){return{income:num('income'),currency:wheelValues.incomeCurrency,period:wheelValues.period,days:num('days'),hours:num('hours')}}
function fillProfile(p){if(!p)return;$('income').value=p.income;$('days').value=p.days;$('hours').value=p.hours;selectWheel('incomeCurrency',p.currency);selectWheel('period',p.period);updateFormButtons()}
async function fetchFx(base,force=false){if(!force&&state.fx?.base===base&&Date.now()-state.fx.savedAt<C.fxMaxAgeMs)return clone(state.fx);const r=await fetch(C.fxEndpoint+encodeURIComponent(base));const d=await r.json();if(d.result!=='success'||!d.rates)throw Error('fx');return{base,rates:d.rates,updated:d.time_last_update_unix||Math.floor(Date.now()/1000),savedAt:Date.now()}}
async function ensureCurrentFx(force=false){if(!state.profile)return;try{state.fx=await fetchFx(state.profile.currency,force);save();$('fxStatus').textContent=`Курсы валют: ${new Date(state.fx.updated*1000).toLocaleDateString('ru-RU')}`}catch{$('fxStatus').textContent=state.fx?.base===state.profile.currency?'Используем последний сохранённый курс.':'В своей валюте считать можно. Для других нужен интернет.'}}
async function saveProfile(){if(!validateFields([{input:$('income'),label:'отправную сумму',emptyKey:'requiredIncome',invalidKey:'invalidIncome',valid:validNumber},{input:$('days'),label:'рабочие дни',emptyKey:'requiredDays',invalidKey:'invalidDays',valid:validNumber},{input:$('hours'),label:'рабочие часы',emptyKey:'requiredHours',invalidKey:'invalidHours',valid:validNumber}]))return;const next=profileFromForm(),old=state.profile;if(!Calc.isValidProfile(next))return;let mode='new';if(old){mode=await dialog({title:'Новый ритм сохранён. Что пересчитать?',text:'Можно применить изменения только к новым карточкам или обновить всё активное. Без твоего выбора старые результаты не изменятся.',actions:[{label:'Отменить изменения',value:'cancel'},{label:'Только новые карточки',value:'new'},{label:'Пересчитать всё активное',value:'all',primary:true}]});if(!mode||mode==='cancel'){fillProfile(old);return}}state.profile=next;await ensureCurrentFx(old?.currency!==next.currency);if(mode==='all'){activeCalcs().forEach(c=>{c.profile=clone(next);c.fx=state.fx?clone(state.fx):c.fx});activeProjects().forEach(p=>p.calculations.forEach(c=>{c.profile=clone(next);c.fx=state.fx?clone(state.fx):c.fx}));toast('Новый ритм принят. Всё активное пересчитано.')}save();$('profileEditor').classList.add('hidden');$('converter').classList.remove('hidden');$('bottomNav').classList.remove('hidden');selectWheel('itemCurrency',next.currency);renderAll()}

function autoTitle(a){return a.length===1?a[0].name:a.slice(0,2).map(x=>x.name).join(' + ')+(a.length>2?` + ещё ${a.length-2}`:'')}
function summaryOfItems(a,p=state.profile,fx=state.fx){return Calc.calculationSummary({items:a,profile:p,fx})}
function itemHtml(it,p,fx,u,removable=false){const s=Calc.itemSummary(it,p,fx),base=s.money,meta=`${Calc.formatNumber(it.qty,2)} × ${Calc.money(it.price,it.currency)}${it.currency!==p.currency&&Number.isFinite(base)?` ≈ ${Calc.money(base,p.currency)}`:''}`;return `<div class="item-card" data-item-id="${it.id}"><div class="item-head"><div class="item-title"></div>${removable?'<button class="remove-button" type="button" aria-label="Удалить">×</button>':''}</div><div class="item-result">${Calc.smart(Calc.unitValue(s.hours,u,p),u)}</div><div class="item-meta">${meta}</div></div>`}
function renderItemList(box,a,p,fx,u,removable=false){box.innerHTML='';a.forEach(it=>{const holder=document.createElement('div');holder.innerHTML=itemHtml(it,p,fx,u,removable);const card=holder.firstElementChild;card.querySelector('.item-title').textContent=it.name;if(removable)card.querySelector('.remove-button').onclick=()=>{items=items.filter(x=>x.id!==it.id);renderCurrent()};box.append(card)})}
function renderCurrent(){if(!state.profile)return;const n=items.length;$('currentTitle').textContent=n?`${n} ${n===1?'позиция':n<5?'позиции':'позиций'}`:'Пока пусто';$('clearItems').classList.toggle('hidden',!n);$('saveCalculation').classList.toggle('hidden',!n);$('currentUnitPicker').classList.toggle('hidden',!n);if(!n)$('itemsList').innerHTML='<div class="empty-state"><strong>Пока здесь тихо.</strong>Добавь первую хотелку — посмотрим, сколько времени она задумала съесть.</div>';else renderItemList($('itemsList'),items,state.profile,state.fx,unit,true);const total=summaryOfItems(items);$('totalCard').classList.toggle('hidden',n<2);if(n>=2){$('totalValue').textContent=Calc.smart(Calc.unitValue(total.hours,unit,state.profile),unit);$('totalMoney').textContent=Number.isFinite(total.money)?`≈ ${Calc.money(total.money,state.profile.currency)}`:''}}
async function addItem(){if(!validateFields([{input:$('itemName'),label:'название хотелки',emptyKey:'requiredItemName'},{input:$('itemPrice'),label:'сумму на ценнике',emptyKey:'requiredItemPrice',invalidKey:'invalidItemPrice',valid:validNumber},{input:$('itemQty'),label:'количество',emptyKey:'requiredItemQty',invalidKey:'invalidItemQty',valid:validNumber}]))return;if(wheelValues.itemCurrency!==state.profile.currency&&(!state.fx||state.fx.base!==state.profile.currency||!state.fx.rates?.[wheelValues.itemCurrency])){await ensureCurrentFx(true);if(!state.fx?.rates?.[wheelValues.itemCurrency])return toast('Не удалось получить курс этой валюты.')}const item={id:S.uid('item'),name:$('itemName').value.trim(),price:num('itemPrice'),qty:num('itemQty'),currency:wheelValues.itemCurrency};magic('calculate',()=>{items.push(item);$('itemName').value='';$('itemPrice').value='';$('itemQty').value='';updateFormButtons();renderCurrent();toast(null,'itemAdded')})}
function snapshot(){return{id:S.uid('calc'),sourceId:null,createdAt:stamp(),updatedAt:stamp(),archivedAt:null,status:'favorite',type:'calculation',title:autoTitle(items),items:clone(items),profile:clone(state.profile),fx:state.fx?clone(state.fx):null,displayUnit:unit}}
function saveCalculation(){if(!items.length)return;state.calculations.unshift(snapshot());save();items=[];$('itemName').value='';$('itemPrice').value='';$('itemQty').value='';renderAll();toast(null,'favoriteSaved')}

function date(v){return new Date(v).toLocaleDateString('ru-RU')}
function empty(title,text){return `<div class="empty-state"><strong>${title}</strong>${text}</div>`}
function bindLongPress(card,id){let t,x,y;card.onpointerdown=e=>{x=e.clientX;y=e.clientY;t=setTimeout(()=>{card.dataset.held='1';enterSelection(id)},C.cardHoldMs)};card.onpointermove=e=>{if(Math.abs(e.clientX-x)>8||Math.abs(e.clientY-y)>8)clearTimeout(t)};card.onpointerup=card.onpointercancel=()=>clearTimeout(t)}
function renderFavorites(){const list=activeCalcs(),box=$('favoritesList');$('clearFavorites').classList.toggle('hidden',!list.length||selectionMode);box.classList.toggle('selection-mode',selectionMode);box.innerHTML='';if(!list.length){box.innerHTML=empty('Здесь пока ничего не припрятано.','Добавь карточку через «Хочу — могу?», и она появится здесь.');updateSelection();return}list.forEach(c=>{const s=Calc.calculationSummary(c),u=c.displayUnit||'hours',card=document.createElement('article');card.className='saved-card'+(selected.has(c.id)?' selected':selectionMode?' selection-muted':'');card.dataset.id=c.id;card.innerHTML=`<div class="saved-card-grid"><div><div class="saved-title"></div><div class="saved-meta">${date(c.createdAt)} · ${c.items.length} поз.</div><div class="saved-summary">${Calc.smart(Calc.unitValue(s.hours,u,c.profile),u)}</div></div><button class="dots-button" type="button" aria-label="Действия">•••</button><div class="selection-mark">${selected.has(c.id)?'✓':''}</div></div>`;card.querySelector('.saved-title').textContent=c.title;card.onclick=e=>{if(card.dataset.held){delete card.dataset.held;return}if(e.target.closest('.dots-button'))return actionCalculation(c);selectionMode?toggleSelected(c.id):openFavorite(c.id)};bindLongPress(card,c.id);box.append(card)});updateSelection()}
function enterSelection(id){selectionMode=true;selected.add(id);renderFavorites();try{navigator.vibrate?.(8)}catch{}}
function toggleSelected(id){selected.has(id)?selected.delete(id):selected.add(id);if(!selected.size)selectionMode=false;renderFavorites()}
function updateSelection(){const n=selected.size,onFavorites=currentScreen()==='Favorites',canCombine=onFavorites&&selectionMode&&n>=2;$('selectionBar').classList.toggle('hidden',!canCombine);$('selectionHint').classList.toggle('hidden',!onFavorites||!selectionMode||n!==1);$('selectionBarCount').textContent=`Выбрано: ${n}`}
function exitSelection(){selectionMode=false;selected.clear();renderFavorites()}
function openFavorite(id){openedFavorite=id;$('favoritesListView').classList.add('hidden');$('favoriteDetailView').classList.remove('hidden');selectWheel('favoriteUnit',find(state.calculations,id)?.displayUnit||'hours');renderFavoriteDetail();scrollTo({top:0})}
function closeFavorite(){$('favoriteDetailView').classList.add('hidden');$('favoritesListView').classList.remove('hidden');openedFavorite=null;renderFavorites()}
function renderFavoriteDetail(){const c=find(state.calculations,openedFavorite);if(!c)return;const u=c.displayUnit||'hours',s=Calc.calculationSummary(c);$('favoriteDetailTitle').textContent=c.title;$('favoriteDetailMeta').textContent=`${date(c.createdAt)} · ${c.items.length} поз.`;renderItemList($('favoriteDetailItems'),c.items,c.profile,c.fx,u);$('favoriteDetailTotalCard').classList.toggle('hidden',c.items.length<2);if(c.items.length>=2){$('favoriteDetailTotal').textContent=Calc.smart(Calc.unitValue(s.hours,u,c.profile),u);$('favoriteDetailMoney').textContent=Calc.money(s.money,c.profile.currency)}}

async function renameCalc(c){const name=await ask('Переименовать','Как теперь назвать эту карточку?',c.title);if(!name)return;c.title=name;c.updatedAt=stamp();state.projects.forEach(p=>p.calculations.filter(x=>x.sourceId===c.id).forEach(x=>x.title=name));save();renderAll();toast(null,'renamed')}
async function editCalc(c){const title=document.createElement('input');title.className='dialog-input';title.value=c.title;title.placeholder='Название карточки';title.required=true;title.setAttribute('aria-required','true');const list=document.createElement('div');list.className='editor-list';const draft=clone(c.items);const body=document.createElement('div');body.append(title,list);function rows(){list.innerHTML='';draft.forEach((it,i)=>{const row=document.createElement('div');row.className='editor-row';row.innerHTML='<input class="ename" maxlength="80" placeholder="Название" required aria-required="true"><input class="eprice" inputmode="decimal" placeholder="Цена" required aria-required="true"><select></select><button type="button" aria-label="Удалить позицию">×</button>';const nameInput=row.querySelector('.ename'),priceInput=row.querySelector('.eprice');nameInput.value=it.name;priceInput.value=it.price;priceInput.dataset.number='decimal';priceInput.dataset.min='0.01';priceInput.dataset.max='1000000000000000';Object.entries(C.currencies).forEach(([v,l])=>row.querySelector('select').add(new Option(l,v)));row.querySelector('select').value=it.currency;nameInput.oninput=e=>it.name=e.target.value;priceInput.oninput=e=>{sanitize(e.target);it.price=Number(e.target.value)};row.querySelector('select').onchange=e=>it.currency=e.target.value;row.querySelector('button').onclick=()=>{draft.splice(i,1);rows()};list.append(row)})}rows();const canSave=()=>Boolean(draft.length&&title.value.trim()&&[...list.querySelectorAll('.editor-row')].every(row=>row.querySelector('.ename').value.trim()&&validNumber(row.querySelector('.eprice')))),validate=()=>{if(!draft.length){toast(null,'requiredCardItem');return false}const rules=[{input:title,label:'название карточки',emptyKey:'requiredTitle'}];list.querySelectorAll('.editor-row').forEach((row,i)=>{rules.push({input:row.querySelector('.ename'),label:`название позиции ${i+1}`,emptyKey:'requiredItemName'},{input:row.querySelector('.eprice'),label:`цену позиции ${i+1}`,emptyKey:'requiredItemPrice',invalidKey:'invalidItemPrice',valid:validNumber})});return validateFields(rules)},ok=await dialog({title:'Изменить детали',text:'Исправь название, стоимость или валюту.',body,actions:[{label:'Отмена',value:false},{label:'Сохранить изменения',value:true,primary:true,enabled:canSave,validate}]});if(!ok)return;c.title=title.value.trim();c.items=draft;c.updatedAt=stamp();state.projects.forEach(p=>p.calculations.filter(x=>x.sourceId===c.id).forEach(x=>{x.title=c.title;x.items=clone(c.items);x.updatedAt=stamp()}));save();renderAll();toast(null,'edited')}
async function recalcCalc(c){if(!await confirm('Пересчитать по текущему ритму?','Карточка будет пересчитана по твоим нынешним исходным данным. Её сохранённый результат будет заменён.','Пересчитать'))return;c.profile=clone(state.profile);if(c.profile.currency!==c.fx?.base)try{c.fx=await fetchFx(c.profile.currency,true)}catch{return toast('Не удалось получить свежий курс. Ничего не изменено.')}c.updatedAt=stamp();save();renderAll();toast('Карточка пересчитана по текущему ритму.')}
async function updateCalcFx(c){if(!await confirm('Обновить курс этой карточки?','Мы возьмём актуальный курс валют и пересчитаем результат. Текущее значение будет заменено.','Обновить и пересчитать'))return;magic('fx',async()=>{try{c.fx=await fetchFx(c.profile.currency,true);c.updatedAt=stamp();save();renderAll();toast('Курс обновлён. Карточка пересчитана.')}catch{toast('Не удалось получить свежий курс. Ничего не изменено.')}})}
function archiveCalc(c){c.status='archived';c.archivedAt=stamp();c.updatedAt=stamp();save();if(openedFavorite)closeFavorite();renderAll();toast(null,'archived')}
async function deleteCalc(c){const used=state.projects.some(p=>p.calculations.some(x=>x.sourceId===c.id)),text=used?'В «Избранном» карточка исчезнет, но останется внутри уже собранных «Больших планов».':'Она будет удалена с этого устройства. Вернуть её не получится.';if(!await confirm('Убрать карточку?',text,'Убрать'))return;state.calculations=state.calculations.filter(x=>x.id!==c.id);save();if(openedFavorite)closeFavorite();renderAll();toast(null,'deleted')}
function actionCalculation(c){sheet(c.title,[{label:'Открыть',run:()=>openFavorite(c.id)},{label:'Выбрать',run:()=>enterSelection(c.id)},{label:'Переименовать',run:()=>renameCalc(c)},{label:'Изменить детали',run:()=>editCalc(c)},{label:'Пересчитать по текущему ритму',run:()=>recalcCalc(c)},{label:'Обновить курс валют',run:()=>updateCalcFx(c)},{label:'Добавить в «Большой план»',run:()=>addOneToProject(c)},{label:'Переместить в Архив',run:()=>archiveCalc(c)},{label:'Удалить',danger:true,run:()=>deleteCalc(c)}])}

async function combine(){const chosen=activeCalcs().filter(c=>selected.has(c.id));if(chosen.length<2)return;const name=await ask('Новый большой план','Как назовём то, что получилось?','Новый большой план','project');if(!name)return;state.projects.unshift({id:S.uid('project'),createdAt:stamp(),updatedAt:stamp(),archivedAt:null,status:'active',type:'project',title:name,displayUnit:'hours',calculations:chosen.map(c=>({...clone(c),id:S.uid('pc'),sourceId:c.id,status:'favorite'}))});save();exitSelection();renderAll();toast(null,'projectSaved')}
async function addOneToProject(c){const projects=activeProjects();if(!projects.length)return toast('Сначала собери большой план минимум из двух карточек.');sheet('Выбери большой план',projects.map(p=>({label:p.title,run:()=>{if(p.calculations.some(x=>x.sourceId===c.id))return toast('Эта карточка уже есть в выбранном плане.');p.calculations.push({...clone(c),id:S.uid('pc'),sourceId:c.id});p.updatedAt=stamp();save();renderAll();toast('Карточка добавлена в «Большой план».')}})))}
function renderProjects(){const list=activeProjects(),box=$('projectsList');$('clearProjects').classList.toggle('hidden',!list.length);box.innerHTML='';if(!list.length){box.innerHTML=empty('Больших планов пока нет.','Выбери минимум две карточки в «Избранном» и собери их вместе.');return}list.forEach(p=>{const s=Calc.projectSummary(p),first=p.calculations[0]?.profile||state.profile,u=p.displayUnit||'hours',card=document.createElement('article');card.className='project-card';card.innerHTML=`<div class="saved-card-grid"><div><div class="saved-title"></div><div class="saved-meta">${date(p.createdAt)} · ${p.calculations.length} карточек</div><div class="saved-summary">${first?Calc.smart(Calc.unitValue(s.hours,u,first),u):'—'}</div></div><button class="dots-button" type="button">•••</button></div>`;card.querySelector('.saved-title').textContent=p.title;card.onclick=e=>e.target.closest('.dots-button')?actionProject(p):openProject(p.id);box.append(card)})}
function openProject(id){openedProject=id;$('projectsListView').classList.add('hidden');$('projectDetailView').classList.remove('hidden');selectWheel('projectUnit',find(state.projects,id)?.displayUnit||'hours');renderProjectDetail();scrollTo({top:0})}
function closeProject(){$('projectDetailView').classList.add('hidden');$('projectsListView').classList.remove('hidden');openedProject=null;renderProjects()}
function renderProjectDetail(){const p=find(state.projects,openedProject);if(!p)return;const u=p.displayUnit||'hours',s=Calc.projectSummary(p),first=p.calculations[0]?.profile||state.profile;$('projectDetailTitle').textContent=p.title;$('projectDetailMeta').textContent=`${date(p.createdAt)} · ${p.calculations.length} карточек`;$('projectDetailGroups').innerHTML='';p.calculations.forEach(c=>{const cs=Calc.calculationSummary(c),g=document.createElement('div');g.className='group-card';g.innerHTML=`<div class="group-title"></div><div class="item-meta"></div><div class="group-total">${Calc.smart(Calc.unitValue(cs.hours,u,c.profile),u)}</div>`;g.querySelector('.group-title').textContent=c.title;g.querySelector('.item-meta').textContent=c.items.map(x=>x.name).join(' · ');$('projectDetailGroups').append(g)});$('projectDetailTotalCard').classList.toggle('hidden',p.calculations.length<2);if(p.calculations.length>=2){$('projectDetailTotal').textContent=Calc.smart(Calc.unitValue(s.hours,u,first),u);const same=p.calculations.every(c=>c.profile?.currency===first.currency);$('projectDetailMoney').textContent=same?Calc.money(s.money,first.currency):''}}
async function renameProject(p){const n=await ask('Переименовать','Как теперь назвать этот большой план?',p.title,'project');if(!n)return;p.title=n;p.updatedAt=stamp();save();renderAll();toast(null,'renamed')}
async function rebuildProject(p){const list=activeCalcs(),body=document.createElement('div');body.className='picker-list';const ids=new Set(p.calculations.map(x=>x.sourceId));list.forEach(c=>{const label=document.createElement('label');label.className='picker-option';label.innerHTML='<input type="checkbox"><span><strong></strong><small></small></span>';const check=label.querySelector('input');check.checked=ids.has(c.id);check.onchange=()=>check.checked?ids.add(c.id):ids.delete(c.id);label.querySelector('strong').textContent=c.title;label.querySelector('small').textContent=`${c.items.length} поз.`;body.append(label)});const ok=await dialog({title:'Пересобрать план',text:'Выбери минимум две карточки.',body,actions:[{label:'Отмена',value:false},{label:'Сохранить состав',value:true,primary:true,enabled:()=>ids.size>=2}]});if(!ok||ids.size<2)return;p.calculations=list.filter(c=>ids.has(c.id)).map(c=>({...clone(c),id:S.uid('pc'),sourceId:c.id}));p.updatedAt=stamp();save();renderAll();toast('«Большой план» обновлён.')}
async function updateProjectFx(p){if(!await confirm('Обновить курсы всего плана?','Все позиции внутри этого плана будут пересчитаны по актуальным курсам валют. Результат может как увеличиться, так и уменьшиться.','Обновить весь план'))return;magic('fx',async()=>{try{const cache={};for(const c of p.calculations){cache[c.profile.currency]??=await fetchFx(c.profile.currency,true);c.fx=clone(cache[c.profile.currency])}p.updatedAt=stamp();save();renderAll();toast('Курсы обновлены. «Большой план» снова в настоящем.')}catch{toast('Не удалось обновить курсы. Ничего не изменено.')}})}
async function recalcProject(p){if(!await confirm('Пересчитать весь план по текущему ритму?','Все позиции этого плана будут пересчитаны по нынешнему рабочему ритму. Другие планы и карточки не изменятся.','Пересчитать'))return;let fresh=null;if(p.calculations.some(c=>c.profile.currency!==state.profile.currency))try{fresh=await fetchFx(state.profile.currency,true)}catch{return toast('Не удалось получить свежий курс. Ничего не изменено.')}p.calculations.forEach(c=>{c.profile=clone(state.profile);if(fresh)c.fx=clone(fresh)});p.updatedAt=stamp();save();renderAll();toast('«Большой план» пересчитан по текущему ритму.')}
function archiveProject(p){p.status='archived';p.archivedAt=stamp();save();if(openedProject)closeProject();renderAll();toast(null,'archived')}
async function deleteProject(p){if(!await confirm('Удалить большой план?','Сам план исчезнет, но его карточки останутся в «Избранном».','Удалить'))return;state.projects=state.projects.filter(x=>x.id!==p.id);save();if(openedProject)closeProject();renderAll();toast(null,'deleted')}
function actionProject(p){sheet(p.title,[{label:'Открыть',run:()=>openProject(p.id)},{label:'Переименовать',run:()=>renameProject(p)},{label:'Пересобрать план',run:()=>rebuildProject(p)},{label:'Пересчитать по текущему ритму',run:()=>recalcProject(p)},{label:'Обновить курсы плана',run:()=>updateProjectFx(p)},{label:'Переместить в Архив',run:()=>archiveProject(p)},{label:'Удалить',danger:true,run:()=>deleteProject(p)}])}

function renderArchive(){document.querySelectorAll('[data-archive-tab]').forEach(b=>b.classList.toggle('active',b.dataset.archiveTab===archiveTab));const box=$('archiveList'),list=archiveTab==='calculations'?state.calculations.filter(x=>x.status==='archived'):state.projects.filter(x=>x.status==='archived');box.innerHTML='';if(!list.length){box.innerHTML=empty('В Архиве пока пусто.','Здесь будут отдыхать карточки и планы, которые ты решил не удалять.');return}list.forEach(x=>{const card=document.createElement('article');card.className='archive-card';card.innerHTML=`<div class="saved-card-grid"><div><div class="saved-title"></div><div class="saved-meta">В Архиве с ${date(x.archivedAt||x.updatedAt)}</div></div><button class="dots-button" type="button">•••</button></div>`;card.querySelector('.saved-title').textContent=x.title;card.onclick=()=>archiveActions(x,archiveTab);box.append(card)})}
function archiveActions(x,type){const isCalc=type==='calculations';sheet(x.title,[{label:isCalc?'Вернуть в «Избранное»':'Вернуть в «Большие планы»',run:()=>{x.status=isCalc?'favorite':'active';x.archivedAt=null;x.updatedAt=stamp();save();renderAll();toast(null,'restored')}},{label:isCalc?'Обновить курс валют':'Обновить курсы плана',run:()=>isCalc?updateCalcFx(x):updateProjectFx(x)},{label:'Удалить навсегда',danger:true,run:async()=>{if(!await confirm('Удалить навсегда?','Вернуть этот элемент после удаления не получится.','Удалить'))return;state[type]=state[type].filter(v=>v.id!==x.id);save();renderArchive();toast(null,'deleted')}}])}
function openArchive(tab='calculations'){previousScreen=currentScreen();archiveTab=tab;switchScreen('Archive')}

function faq(){const device=/iPhone/i.test(navigator.userAgent)?'этом iPhone':'этом устройстве';const data=[['Что вообще происходит?','My Rate переводит стоимость вещей и планов в твоё рабочее время. Ты задаёшь отправную сумму и привычный рабочий ритм, а остальная математика происходит за кулисами. Это не финансовый прогноз — это другой способ посмотреть на ценник.'],['Почему мне не показывают стоимость моего часа?','Потому что мы намеренно не выставляем промежуточную формулу напоказ. Ты видишь итог, а математика спокойно делает свою работу за сценой.'],['Как считается время?','Мы учитываем выбранный период, количество рабочих дней в неделе и часов в рабочем дне. В году используется 52 рабочие недели, а месяц считается как средняя часть года.'],['Насколько точен результат?','Результат приблизительный. Реальная стоимость времени зависит от отпусков, премий, переработок и других обстоятельств. My Rate предлагает точку зрения, а не абсолютную истину.'],['Куда уходят мои данные?',`Никуда. Мы не отправляем на сервер исходную сумму, карточки или «Большие планы». Всё остаётся на ${device}. Если удалить данные сайта с устройства, «Избранное» и «Большие планы» тоже исчезнут.`],['Откуда берутся курсы валют?','Используются информационные курсы Exchange Rate API. Они обновляются приблизительно раз в сутки. Сохранённая карточка запоминает курс, использованный при создании.'],['«Избранное» и «Большие планы» — в чём разница?','«Избранное» хранит отдельные карточки. «Большой план» объединяет несколько карточек и показывает их вместе. Общий итог появляется минимум для двух позиций.'],['Как изменить карточку?','Нажми на ••• или ненадолго задержи палец на карточке. «Переименовать» меняет название, а «Изменить детали» — цену, количество и валюту.'],['Почему барабан не крутится сразу?','Так он не мешает прокручивать страницу. Быстро проведи пальцем — страница продолжит движение. Немного задержи палец, дождись подсветки и потяни — начнёт вращаться барабан.'],['Можно убрать анимацию и реплики?','Да. В настройках можно отдельно отключить «Магию пересчёта» и «Шутки и реплики». Расчёты продолжат работать.'],['Кто всё это устроил?','My Rate — первый продукт PROBA. Небольшой эксперимент о том, как переводить желания из денег в собственное время. Designed & created by PROBA.'],['Что будет дальше?','Есть мысль однажды перевести время в социальных сетях в минуты, дни и даже годы. Пока это только намёк.']];$('faqContent').innerHTML='';data.forEach(([q,a])=>{const d=document.createElement('details');d.className='faq-item';d.innerHTML='<summary></summary><div class="faq-answer"></div>';d.querySelector('summary').textContent=q;d.querySelector('.faq-answer').textContent=a;$('faqContent').append(d)})}
function currentScreen(){return document.querySelector('.screen.active')?.id.replace('screen','')||'Current'}
function switchScreen(name){closeHelp();dismissKeyboard();if(name!=='Favorites'&&(selectionMode||selected.size)){selectionMode=false;selected.clear()}document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===`screen${name}`));document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.screen===name));$('bottomNav').classList.toggle('hidden',!state.profile||['Archive','Settings','Faq'].includes(name));$('appFooter').classList.toggle('hidden',['Archive','Settings','Faq'].includes(name));if(name==='Favorites'){closeFavorite();renderFavorites()}if(name==='Projects'){closeProject();renderProjects()}if(name==='Archive')renderArchive();if(name==='Faq')faq();updateSelection();scrollTo({top:0})}
function renderAll(){renderCurrent();renderFavorites();renderProjects();if(currentScreen()==='Archive')renderArchive();if(openedFavorite)renderFavoriteDetail();if(openedProject)renderProjectDetail();$('magicToggle').checked=state.settings.magic;$('jokesToggle').checked=state.settings.jokes;updateFormButtons()}

async function updateAllFx(){const includeArchive=await dialog({title:'Обновить все курсы?',text:`Карточки в «Избранном» и активные «Большие планы» будут пересчитаны. Будет обновлено: ${activeCalcs().length} карточек и ${activeProjects().length} больших планов.`,actions:[{label:'Не надо',value:false},{label:'Только активное',value:'active',primary:true},{label:'Включая Архив',value:'all'}]});if(!includeArchive)return;magic('fx',async()=>{const calcs=state.calculations.filter(x=>includeArchive==='all'||x.status!=='archived'),projects=state.projects.filter(x=>includeArchive==='all'||x.status!=='archived'),bases=new Set([...calcs.map(x=>x.profile?.currency),...projects.flatMap(p=>p.calculations.map(x=>x.profile?.currency))].filter(Boolean)),cache={};try{for(const b of bases)cache[b]=await fetchFx(b,true);calcs.forEach(x=>x.fx=clone(cache[x.profile.currency]));projects.forEach(p=>p.calculations.forEach(x=>x.fx=clone(cache[x.profile.currency])));save();renderAll();toast('Всё выбранное пересчитано по свежим курсам.')}catch{toast('Не удалось обновить курсы. Ничего не изменено.')}})}

document.querySelectorAll('[data-number]').forEach(i=>{i.addEventListener('input',()=>sanitize(i));i.addEventListener('paste',()=>setTimeout(()=>sanitize(i)))});
document.addEventListener('input',e=>{if(e.target.matches?.('input, textarea, select')){e.target.classList.remove('field-error');e.target.removeAttribute('aria-invalid');updateFormButtons()}});
document.addEventListener('click',e=>{const help=e.target.closest('[data-help]');if(help){e.stopPropagation();showHelp(help);return}if(!e.target.closest('#helpPopover'))closeHelp();const nav=e.target.closest('[data-screen]');if(nav)switchScreen(nav.dataset.screen);const arch=e.target.closest('[data-open-archive]');if(arch)openArchive(arch.dataset.openArchive)});
document.addEventListener('focusin',e=>{if(e.target.matches('input, textarea, select')){closeHelp();document.body.classList.add('keyboard-open')}});document.addEventListener('focusout',()=>setTimeout(()=>{if(!document.activeElement?.matches?.('input, textarea, select'))document.body.classList.remove('keyboard-open')},120));addEventListener('scroll',closeHelp,{passive:true});
$('saveProfile').onclick=saveProfile;$('addItem').onclick=addItem;$('clearItems').onclick=async()=>{if(await confirm('Очистить всё на этом экране?','Текущие позиции исчезнут. Настройки твоего рабочего ритма останутся на месте.','Очистить')){items=[];renderCurrent()}};$('saveCalculation').onclick=saveCalculation;
$('cancelSelection').onclick=exitSelection;$('combineSelected').onclick=combine;$('clearFavorites').onclick=async()=>{const a=activeCalcs();if(!a.length)return;if(await confirm('Очистить всё «Избранное»?','Все карточки исчезнут из «Избранного». То, что уже входит в «Большие планы», останется внутри них.','Очистить')){state.calculations=state.calculations.filter(x=>x.status==='archived');save();renderAll();toast(null,'deleted')}};
$('clearProjects').onclick=async()=>{const a=activeProjects();if(!a.length)return;if(await confirm('Удалить все большие планы?','Активные планы будут удалены. Карточки в «Избранном» и содержимое Архива останутся на месте.','Удалить всё')){state.projects=state.projects.filter(x=>x.status==='archived');save();renderAll();toast(null,'deleted')}};
$('favoriteBack').onclick=closeFavorite;$('favoriteDetailMenu').onclick=()=>{const c=find(state.calculations,openedFavorite);if(c)actionCalculation(c)};$('projectBack').onclick=closeProject;$('projectDetailMenu').onclick=()=>{const p=find(state.projects,openedProject);if(p)actionProject(p)};
$('archiveBack').onclick=()=>switchScreen(previousScreen);document.querySelectorAll('[data-archive-tab]').forEach(b=>b.onclick=()=>{archiveTab=b.dataset.archiveTab;renderArchive()});
{const gear=$('settingsButton'),leaveSettings=()=>switchScreen(previousScreen&&previousScreen!=='Settings'?previousScreen:'Current');let hold,x,y;gear.onpointerdown=e=>{x=e.clientX;y=e.clientY;hold=setTimeout(()=>{gear.dataset.held='1';sheet('Быстрые настройки',[{label:'Подкрутить мой рабочий ритм',run:()=>{$('editProfile').click()}},{label:state.settings.magic?'Убрать магию пересчёта':'Вернуть магию пересчёта',run:()=>{state.settings.magic=!state.settings.magic;save();renderAll()}},{label:state.settings.jokes?'Убавить разговорчивость':'Вернуть шутки и реплики',run:()=>{state.settings.jokes=!state.settings.jokes;save();renderAll()}},{label:'Что за магия?',run:()=>{previousScreen=currentScreen();switchScreen('Faq')}}])},C.cardHoldMs)};gear.onpointermove=e=>{if(Math.abs(e.clientX-x)>8||Math.abs(e.clientY-y)>8)clearTimeout(hold)};gear.onpointerup=gear.onpointercancel=()=>clearTimeout(hold);gear.onclick=()=>{if(gear.dataset.held){delete gear.dataset.held;return}if(currentScreen()==='Settings'){leaveSettings();return}previousScreen=currentScreen();switchScreen('Settings')};$('settingsBack').onclick=leaveSettings;}
$('openFaq').onclick=()=>{previousScreen='Settings';switchScreen('Faq')};$('faqBack').onclick=()=>switchScreen(previousScreen);
$('editProfile').onclick=()=>{previousScreen='Settings';fillProfile(state.profile);$('profileEditor').classList.remove('hidden');$('converter').classList.add('hidden');switchScreen('Current')};$('magicToggle').onchange=e=>{state.settings.magic=e.target.checked;save()};$('jokesToggle').onchange=e=>{state.settings.jokes=e.target.checked;save()};$('updateAllFx').onclick=updateAllFx;

wheelValues.unit=unit;wheelValues.favoriteUnit='hours';wheelValues.projectUnit='hours';setupWheel('incomeCurrency',C.currencies);setupWheel('itemCurrency',C.currencies);setupWheel('period',C.periods);setupWheel('unit',C.units,v=>magic('calculate',()=>{unit=v;renderCurrent()}));setupWheel('favoriteUnit',C.units,v=>{const c=find(state.calculations,openedFavorite);if(c){magic('calculate',()=>{c.displayUnit=v;save();renderFavoriteDetail()})}});setupWheel('projectUnit',C.units,v=>{const p=find(state.projects,openedProject);if(p){magic('calculate',()=>{p.displayUnit=v;save();renderProjectDetail()})}});
if(state.profile){fillProfile(state.profile);$('profileEditor').classList.add('hidden');$('converter').classList.remove('hidden');$('bottomNav').classList.remove('hidden');selectWheel('itemCurrency',state.profile.currency);ensureCurrentFx(false).then(renderAll)}else{$('profileEditor').classList.remove('hidden');$('converter').classList.add('hidden');$('bottomNav').classList.add('hidden')}
renderAll();
setupIntroLifecycle();
runIntro('launch');
})();
